name: copilot-deploy-pipeline

on:
  workflow_dispatch:
  push:
    branches: ["feature-semantic-memory"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
  build-webapi:
    uses: ./.github/workflows/copilot-build-backend.yml

  build-memorypipeline:
    uses: ./.github/workflows/copilot-build-memorypipeline.yml

  feature-semantic-memory:
    needs: [build-webapi, build-memorypipeline]
    uses: ./.github/workflows/copilot-deploy-environment.yml
    with:
      ENVIRONMENT: feature-semantic-memory
      WEBAPI_ARTIFACT_NAME: ${{needs.build-webapi.outputs.artifact}}
      MEMORYPIPELINE_ARTIFACT_NAME: ${{needs.build-memorypipeline.outputs.artifact}}
    secrets:
      AZURE_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
      AZURE_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
      AZURE_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      AZURE_OPENAI_ENDPOINT: ${{secrets.AZURE_OPENAI_ENDPOINT}}
